org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# forge=true
# fabric=true
neoforge=true

mod_id=scylla_core
mod_name=Scylla Core
mod_license=All Rights Reserved
mod_version=1.0.69
mod_group_id=com.github.syren_dev_tech
mod_authors=ChrisOfNormandy
mod_description=A library mod for Minecraft modding.

# Minecraft Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
mapping_channel=parchment
parchment_version=2024.11.17

# Forge Properties
forge_version=52.1.0
forge_version_range=[52,)
loader_version_range=[52,)

# Fabric Properties
fabric_loader_version=0.16.0
fabric_api_version=0.93.0+1.21.1
yarn_mappings_version=1.21.1+build.1
loom_version=1.6.0

# NeoForge Properties
neoforge_version=21.1.219
neoforge_version_range=[21.6,)
neoforge_loader_version_range=[4,)

# Dependency Properties
geckolib_version=4.8.3